compilation:
	clang++ -std=c++17 -Wall -Wextra -Wpedantic -Wshadow -Wconversion -g -O0 -fno-omit-frame-pointer -fsanitize=address,undefined -o main.out main.cpp

msvc:
	cl /std:c++17 /W4 /permissive- /Zi /Od /Oy- /EHsc /MDd /Fe:main.exe main.cpp
